### ISSUE TITLE
nrpe-external-master-interface is no longer accessible

### ISSUE THREAD

**Issue by nobuto-m** [juju/layer-index#119]
A charm build started to fail with:
```
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/interfaces/nrpe-external-master.json
2021-12-01 03:37:09.181840 | xenial-medium | charmtools.build.fetchers: Found repo: https://github.com/cmars/nrpe-external-master-interface
...

2021-12-01 03:37:09.899651 | xenial-medium | fatal: could not read Username for 'https://github.com': No such device or address
```

It's probably because https://github.com/cmars/nrpe-external-master-interface is not publicly accessible any longer (deleted or gone private).

**Comment by nobuto-m** [comment]
https://github.com/juju/layer-index/blob/7f1ac248a46afb35833fdde4939357c32682e59b/interfaces/nrpe-external-master.json#L1-L6

**Comment by xavpaice** [comment]
I've found a copy of the code and added it to https://github.com/canonical/nrpe-external-master-interface

**Comment by xavpaice** [comment]
https://github.com/juju/layer-index/pull/120
