### ISSUE TITLE
Move interface-memcache to active maintainer

### ISSUE THREAD

**Issue by jamesbeedy** [juju/layer-index#126]
Hello,

We have this [memcache interface](https://github.com/omnivector-solutions/interface-memcache) that we are not actively using or maintaining.

I'm wondering if we can move this `interface-memcache` to the organization of the who uses it?

@ajkavanagh made the most recent PR on the repo, possibly he has some thoughts here?

Thanks

**Comment by jamesbeedy** [comment]
https://github.com/juju/layer-index/blob/master/interfaces/memcache.json#L4

**Comment by kwmonroe** [comment]
@jamesbeedy ahoy friend!  we did a similar bit for `interface-redis` in https://github.com/juju/layer-index/pull/124. i'm gonna move this under the `canonical` gh org.

**Comment by jamesbeedy** [comment]
Awesome. Thanks!
